-- Importa fotos comerciais já rastreadas no catálogo do O Mercador.
-- Os produtos continuam sem representação visual no editor; esta migration
-- altera somente foto e fabricante. Ofertas e projetos existentes são preservados.

insert into public.manufacturers (id, nome, logo_url, is_demo)
select gen_random_uuid(), source.nome, null, false
from (values ('Ceramfix'), ('Corfio'), ('Docol'), ('Eternit'), ('Fortlev'), ('Inkor'), ('Krona'), ('Portokoll'), ('RCM'), ('Tigre'), ('Vedacit'), ('Weg')) as source(nome)
where not exists (
  select 1 from public.manufacturers where lower(manufacturers.nome) = lower(source.nome)
);

with imported(sku, manufacturer_name, foto_url) as (
values
  ('000014', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-10000l-fortlev.png'),
  ('000017', 'Tigre', '/produtos/tigre/conector-aquatherm-tigre.jpg'),
  ('000035', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('000073', 'RCM', '/produtos/rcm/cabo-flexivel-10-0mm-1kv-hepr-preto-rcm.webp'),
  ('000146', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-5000l-fortlev.png'),
  ('000214', 'Tigre', '/produtos/tigre/conector-macho-ppr-tigre.jpg'),
  ('000230', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('000232', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('000318', 'Krona', '/produtos/krona/tubo-esgoto-serie-reforcada-6m-krona.png'),
  ('000319', 'Krona', '/produtos/krona/tubo-esgoto-serie-reforcada-6m-krona.png'),
  ('000323', 'Krona', '/produtos/krona/joelho-90-esgoto-sr-krona.png'),
  ('000325', 'Krona', '/produtos/krona/joelho-90-esgoto-sr-krona.png'),
  ('000327', 'Krona', '/produtos/krona/joelho-45-esgoto-sr-krona.png'),
  ('000328', 'Krona', '/produtos/krona/joelho-45-esgoto-sr-krona.png'),
  ('000355', 'Krona', '/produtos/krona/juncao-esgoto-sr-krona.png'),
  ('000371', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-12-16-tigre.jpg'),
  ('000379', 'Krona', '/produtos/krona/tubo-esgoto-serie-reforcada-6m-krona.png'),
  ('000385', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('000387', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('000389', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('000425', 'Krona', '/produtos/krona/joelho-90-esgoto-sr-krona.png'),
  ('000427', 'Krona', '/produtos/krona/joelho-90-esgoto-sr-krona.png'),
  ('000445', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('000446', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('000447', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('000448', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('000449', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('000458', 'Krona', '/produtos/krona/joelho-45-esgoto-sr-krona.png'),
  ('000461', 'Corfio', '/produtos/corfio/cabo-pp-500v-3x1-5mm-preto-corfio.png'),
  ('000462', 'Corfio', '/produtos/corfio/cabo-flexivel-bwf-750v-2-5mm-azul-escuro-corfio.png'),
  ('000483', 'Tigre', '/produtos/tigre/joelho-90-aquatherm-tigre.jpg'),
  ('000484', 'Krona', '/produtos/krona/joelho-90-soldavel-rosca-lr-krona.png'),
  ('000485', 'Krona', '/produtos/krona/joelho-90-soldavel-rosca-lr-krona.png'),
  ('000488', 'Tigre', '/produtos/tigre/joelho-90-transicao-aquatherm-tigre.jpg'),
  ('000492', 'Tigre', '/produtos/tigre/te-90-aquatherm-tigre.jpg'),
  ('000493', 'Tigre', '/produtos/tigre/te-reducao-aquatherm-tigre.jpg'),
  ('000494', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('000499', 'Tigre', '/produtos/tigre/curva-90-aquatherm-tigre.jpg'),
  ('000501', 'Krona', '/produtos/krona/curva-45-longa-esgoto-sn-krona.png'),
  ('000502', 'Krona', '/produtos/krona/curva-90-longa-esgoto-sn-krona.png'),
  ('000505', 'Krona', '/produtos/krona/curva-90-curta-esgoto-sn-krona.png'),
  ('000508', 'Krona', '/produtos/krona/engate-plastico-40cm-krona.png'),
  ('000517', 'Krona', '/produtos/krona/te-reducao-esgoto-sn-krona.png'),
  ('000527', 'Docol', '/produtos/docol/valvula-succao-1.jpg'),
  ('000720', 'Fortlev', '/produtos/fortlev/sifao-ajustavel-simples-branco-fortlev.jpg'),
  ('000850', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CZ ARTICO PLUS BD 1KG PORTOKOLL.webp'),
  ('000880', 'Vedacit', '/produtos/vedacit/pro-primer-mantas-base-agua-3-6l-vedacit.jpg'),
  ('001065', 'Portokoll', '/produtos/portokoll/ARGAMASSA SUPER PORCELANATO AC3 20KG PORTOKOLL.webp'),
  ('001139', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL AREIA BD 1KG PORTOKOLL.webp'),
  ('001188', 'Krona', '/produtos/krona/tubo-descida-longo-curva-caixa-descarga-krona.png'),
  ('001189', 'Krona', '/produtos/krona/tubo-descida-joelho-azul-valvula-descarga-krona.png'),
  ('001190', 'Krona', '/produtos/krona/espude-vaso-sanitario-krona.png'),
  ('001211', 'Krona', '/produtos/krona/adaptador-curto-soldavel-krona.png'),
  ('001228', 'Corfio', '/produtos/corfio/cabo-pp-500v-4x1-5mm-preto-corfio.jpg'),
  ('001254', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('001257', 'Krona', '/produtos/krona/te-reducao-soldavel-krona.png'),
  ('001264', 'Krona', '/produtos/krona/joelho-90-soldavel-rosca-lr-krona.png'),
  ('001271', 'Krona', '/produtos/krona/joelho-90-soldavel-bucha-latao-krona.png'),
  ('001281', 'Krona', '/produtos/krona/registro-esfera-soldavel-compacto-krona.png'),
  ('001291', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('001295', 'Krona', '/produtos/krona/juncao-esgoto-sn-krona.png'),
  ('001309', 'Krona', '/produtos/krona/te-reducao-esgoto-sn-krona.png'),
  ('001319', 'Krona', '/produtos/krona/haste-chuveiro-eletrico-krona.png'),
  ('001328', 'Krona', '/produtos/krona/chuveiro-frio-krona.png'),
  ('001363', 'Docol', '/produtos/docol/registro-pressao-docolbase-3-4.jpg'),
  ('001364', 'Docol', '/produtos/docol/registro-gaveta-docolbase-3-4.jpg'),
  ('001423', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CAMURCA BD 1KG PORTOKOLL.webp'),
  ('001551', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-cinza-corfio.png'),
  ('001731', 'Krona', '/produtos/krona/curva-45-soldavel-32mm-krona.jpg'),
  ('001840', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('001857', 'Tigre', '/produtos/tigre/te-reducao-soldavel-tigre.jpg'),
  ('001864', 'Tigre', '/produtos/tigre/te-soldavel-rosca-tigre.jpg'),
  ('001945', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-500l-fortlev.jpg'),
  ('001946', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-1000l-fortlev.jpg'),
  ('001967', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('001988', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('002010', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002032', 'Krona', '/produtos/krona/eletroduto-corrugado-reforcado-laranja-krona.png'),
  ('002060', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002061', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002062', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002065', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-7500l-fortlev.jpg'),
  ('002091', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('002105', 'Vedacit', '/produtos/vedacit/tela-poliester-49cm-50m-vedacit.png'),
  ('002172', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-2000l-fortlev.jpg'),
  ('002176', 'Docol', '/produtos/docol/registro-gaveta-europa-3-4.jpg'),
  ('002267', 'RCM', '/produtos/rcm/cabo-flexivel-2-5mm-preto-rcm.webp'),
  ('002269', 'RCM', '/produtos/rcm/cabo-flexivel-2-5mm-vermelho-rcm.png'),
  ('002272', 'Corfio', '/produtos/corfio/cabo-pp-500v-3x2-5mm-preto-corfio.jpg'),
  ('002273', 'RCM', '/produtos/rcm/cabo-flexivel-4mm-azul-rcm.webp'),
  ('002280', 'RCM', '/produtos/rcm/cabo-flexivel-10-0mm-750-kv-verde-rcm.png'),
  ('002300', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('002301', 'Tigre', '/produtos/tigre/tubo-coletor-esgoto-6m-jei-tigre.jpg'),
  ('002308', 'Docol', '/produtos/docol/registro-gaveta-abnt-1-1-4.jpg'),
  ('002309', 'Docol', '/produtos/docol/registro-gaveta-abnt-3-4.jpg'),
  ('002311', 'Docol', '/produtos/docol/registro-gaveta-europa-1-1-4.jpg'),
  ('002312', 'Docol', '/produtos/docol/registro-gaveta-europa-1-1-2.jpg'),
  ('002313', 'Docol', '/produtos/docol/registro-gaveta-abnt-1-1-2.jpg'),
  ('002314', 'Docol', '/produtos/docol/registro-gaveta-docolbase-1-1-2.jpg'),
  ('002342', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-3000l-fortlev.jpg'),
  ('002364', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('002464', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002475', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sn-6m-fortlev.jpg'),
  ('002506', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('002518', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL BCO BRIL BD 1KG PORTOKOLL.webp'),
  ('002537', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('002541', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO BRANCO 1KG PORTOKOLL.webp'),
  ('002542', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO BEGE 1KG PORTOKOLL.webp'),
  ('002543', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO MARROM 1KG PORTOKOLL - Copia.webp'),
  ('002544', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CZ PLATINA BD 1KG PORTOKOLL.webp'),
  ('002556', 'RCM', '/produtos/rcm/cabo-flexivel-10-0mm-750-kv-azul-rcm.webp'),
  ('002559', 'RCM', '/produtos/rcm/cabo-flexivel-6mm-branco-rcm.png'),
  ('002560', 'RCM', '/produtos/rcm/cabo-flexivel-6mm-verde-rcm.png'),
  ('002607', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-1500l-fortlev.jpg'),
  ('002625', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-amarelo-corfio.png'),
  ('002626', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002627', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002628', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002629', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002630', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002631', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002632', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002633', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002634', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002635', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002636', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002637', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002638', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002639', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002640', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002641', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002642', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002643', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002644', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002645', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002646', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002662', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('002679', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-250l-fortlev.jpg'),
  ('002681', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO CZ ARTICO 1KG PORTOKOLL.webp'),
  ('002682', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO CZ PLATINA 1KG PORTOKOLL.webp'),
  ('002703', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL GRAFITE BD 1KG PORTOKOLL.webp'),
  ('002706', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002713', 'Corfio', '/produtos/corfio/cabo-pp-500v-2x2-5mm-preto-corfio.jpg'),
  ('002714', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-amarelo-corfio.png'),
  ('002715', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002716', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002717', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002718', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002719', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('002720', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('002721', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002734', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('002738', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO CORDA 1KG PORTOKOLL.webp'),
  ('002740', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-310l-fortlev.jpg'),
  ('002741', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-150l-fortlev.jpg'),
  ('002848', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002849', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('002850', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002851', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('002852', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('002866', 'Portokoll', '/produtos/portokoll/ARGAMASSA COL INTERIORES 20 KG PORTOKOLL.webp'),
  ('002895', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('002927', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CAQUI BD 1KG PORTOKOLL.webp'),
  ('002928', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL PATINA CHOCO BD 1KG PORTOKOLL.webp'),
  ('002942', 'Portokoll', '/produtos/portokoll/ARGAMASSA SUPERFLEX AC3 20KG PORTOKOLL.webp'),
  ('002955', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI PISCINA BRANCO 1KG PORTOKOLL.webp'),
  ('003087', 'Corfio', '/produtos/corfio/cabo-pp-500v-2x1-5mm-preto-corfio.jpg'),
  ('003111', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003112', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003113', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('003114', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('003115', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003116', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('003117', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003118', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('003119', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('003120', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003121', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003122', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('003134', 'Krona', '/produtos/krona/juncao-reducao-esgoto-sr-krona.png'),
  ('003148', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('003158', 'Docol', '/produtos/docol/valvula-retencao-horizontal-1-1-4.jpg'),
  ('003166', 'Docol', '/produtos/docol/registro-gaveta-abnt-1.jpg'),
  ('003168', 'Docol', '/produtos/docol/registro-gaveta-abnt-1-2.jpg'),
  ('003169', 'Docol', '/produtos/docol/valvula-retencao-vertical-1-1-4.jpg'),
  ('003196', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('003208', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('003209', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('003210', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003211', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003277', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO PRETO 1KG PORTOKOLL.webp'),
  ('003321', 'Docol', '/produtos/docol/acabamento-valvula-descarga-nova-benefit-cromado.jpg'),
  ('003381', 'Docol', '/produtos/docol/registro-gaveta-europa-1.jpg'),
  ('003403', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('003433', 'Docol', '/produtos/docol/registro-gaveta-docolbase-1.jpg'),
  ('003454', 'Vedacit', '/produtos/vedacit/bianco-18kg-vedacit.png'),
  ('003456', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO GRAFITE 1KG PORTOKOLL.webp'),
  ('003467', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('003469', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CORDA BD 1KG PORTOKOLL.webp'),
  ('003496', 'Weg', '/produtos/weg/modulo-interruptor-intermediario-compose-weg.jpg'),
  ('003503', 'Weg', '/produtos/weg/conjunto-interruptor-paralelo-tomada-10a-compose-weg.png'),
  ('003530', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('003547', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('003550', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('003617', 'Weg', '/produtos/weg/conjunto-tomada-2pt-20a-compose-weg.jpeg'),
  ('003652', 'Eternit', '/produtos/eternit/cumeeira-articulada-superior-ondulada-eternit.jpg'),
  ('003653', 'Eternit', '/produtos/eternit/cumeeira-articulada-inferior-ondulada-eternit.jpg'),
  ('003691', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO CREME 1KG PORTOKOLL.webp'),
  ('003707', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('003722', 'Docol', '/produtos/docol/valvula-retencao-horizontal-1.png'),
  ('003739', 'Weg', '/produtos/weg/conjunto-tomada-2pt-10a-compose-weg.png'),
  ('003747', 'Portokoll', '/produtos/portokoll/rejunte-acrilico-ligamax-gold-cinza-claro-1kg.jpg'),
  ('003754', 'Krona', '/produtos/krona/adesivo-ultraterm-850g-krona.png'),
  ('003755', 'Krona', '/produtos/krona/adesivo-pvc-850g-krona.png'),
  ('003770', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('003771', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003772', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003773', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-amarelo-corfio.png'),
  ('003784', 'Docol', '/produtos/docol/valvula-retencao-vertical-3-4.jpg'),
  ('003785', 'Portokoll', '/produtos/portokoll/ARGAMASSA LIGAMAX AC3 GOLD PERFORMANCE CINZA 20KG.webp'),
  ('003786', 'Portokoll', '/produtos/portokoll/ARGAMASSA COL PISCINAS 20KG PORTOKOLL.webp'),
  ('003805', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-amarelo-corfio.png'),
  ('003806', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-amarelo-corfio.png'),
  ('003807', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-amarelo-corfio.png'),
  ('003808', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-amarelo-corfio.png'),
  ('003826', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('003829', 'Weg', '/produtos/weg/modulo-tomada-2pt-20a-compose-weg.jpg'),
  ('003841', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('003845', 'Fortlev', '/produtos/fortlev/caixa-dagua-polietileno-750l-fortlev.jpg'),
  ('003848', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('003903', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('003911', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('003930', 'Vedacit', '/produtos/vedacit/aditivo-impermeabilizante-18l-vedacit.png'),
  ('003939', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO MARFIM 1KG PORTOKOLL.webp'),
  ('003942', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL MARFIM BD 1KG PORTOKOLL.webp'),
  ('003956', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-cinza-corfio.png'),
  ('003965', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('003979', 'Inkor', '/produtos/inkor/argamassa-superkola-ac3-20-kg-inkor.webp'),
  ('004007', 'Inkor', '/produtos/inkor/argamassa-reparo-estrutural-20kg-inkor.webp'),
  ('004118', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-amarelo-corfio.png'),
  ('004198', 'Inkor', '/produtos/inkor/chapisco-chapiskor-pro-2-20kg-inkor.jpg'),
  ('004199', 'Inkor', '/produtos/inkor/argamassa-autonivelante-cinza-20kg-inkor.webp'),
  ('004229', 'Docol', '/produtos/docol/valvula-retencao-vertical-4.jpg'),
  ('004275', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sr-6m-fortlev.png'),
  ('004276', 'Fortlev', '/produtos/fortlev/tubo-esgoto-sr-6m-fortlev.png'),
  ('004328', 'Inkor', '/produtos/inkor/primer-selador-autonivelante-3-6l-inkor.png'),
  ('004362', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('004363', 'Tigre', '/produtos/tigre/te-reducao-soldavel-tigre.jpg'),
  ('004365', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004389', 'Corfio', '/produtos/corfio/cabo-pp-500v-4x0-75mm-preto-corfio.jpg'),
  ('004407', 'Docol', '/produtos/docol/registro-gaveta-europa-2.jpg'),
  ('004408', 'Docol', '/produtos/docol/registro-gaveta-europa-1-2.jpg'),
  ('004409', 'Docol', '/produtos/docol/valvula-retencao-vertical-2.jpg'),
  ('004424', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('004470', 'Krona', '/produtos/krona/juncao-dupla-esgoto-sn-krona.png'),
  ('004516', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('004517', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('004523', 'Portokoll', '/produtos/portokoll/ARGAMASSA COL MULTIUSO 4 EM 1 20 KG PORTOKOLL.webp'),
  ('004587', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('004603', 'Tigre', '/produtos/tigre/caixa-gordura-dn100-tigre.png'),
  ('004633', 'Tigre', '/produtos/tigre/curva-90-soldavel-tigre.jpg'),
  ('004635', 'Tigre', '/produtos/tigre/curva-90-soldavel-tigre.jpg'),
  ('004637', 'Tigre', '/produtos/tigre/curva-90-soldavel-tigre.jpg'),
  ('004643', 'Tigre', '/produtos/tigre/joelho-45-esgoto-serie-normal-tigre.jpg'),
  ('004646', 'Tigre', '/produtos/tigre/joelho-45-esgoto-serie-normal-tigre.jpg'),
  ('004647', 'Tigre', '/produtos/tigre/joelho-45-esgoto-serie-normal-tigre.jpg'),
  ('004649', 'Tigre', '/produtos/tigre/joelho-45-esgoto-serie-r-dn100-tigre.jpg'),
  ('004654', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('004657', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004658', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004659', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004660', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004661', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004662', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('004663', 'Tigre', '/produtos/tigre/joelho-90-esgoto-com-anel-tigre.jpg'),
  ('004665', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-normal-tigre.jpg'),
  ('004668', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-normal-tigre.jpg'),
  ('004669', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-normal-tigre.jpg'),
  ('004670', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-r-dn100-tigre.jpg'),
  ('004675', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004676', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004677', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004678', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004679', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004680', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004681', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004682', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('004684', 'Tigre', '/produtos/tigre/joelho-90-soldavel-bucha-latao-tigre.jpg'),
  ('004685', 'Tigre', '/produtos/tigre/joelho-90-soldavel-bucha-latao-tigre.jpg'),
  ('004688', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('004690', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-r-tigre.jpg'),
  ('004775', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004778', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('004780', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('004781', 'Tigre', '/produtos/tigre/te-reducao-soldavel-tigre.jpg'),
  ('004782', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004783', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('004784', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('004785', 'Tigre', '/produtos/tigre/curva-90-curta-esgoto-serie-normal-tigre.jpg'),
  ('004787', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('004788', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('004790', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('004794', 'Tigre', '/produtos/tigre/te-soldavel-bucha-latao-tigre.jpg'),
  ('004815', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('004847', 'Docol', '/produtos/docol/valvula-retencao-horizontal-4.jpg'),
  ('004856', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('004875', 'Krona', '/produtos/krona/joelho-90-ultraterm-krona.png'),
  ('004882', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('004888', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('004889', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-18-24-tigre.jpg'),
  ('004895', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('004897', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004898', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('004899', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-marrom-corfio.png'),
  ('004909', 'Tigre', '/produtos/tigre/quadro-distribuicao-sobrepor-12-16-tigre.jpg'),
  ('004910', 'Tigre', '/produtos/tigre/quadro-distribuicao-sobrepor-12-16-tigre.jpg'),
  ('004911', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-27-36-tigre.jpg'),
  ('004941', 'Tigre', '/produtos/tigre/eletroduto-corrugado-tigreflex-reforcado.jpg'),
  ('004942', 'Tigre', '/produtos/tigre/eletroduto-corrugado-tigreflex-reforcado.jpg'),
  ('004943', 'Tigre', '/produtos/tigre/eletroduto-corrugado-tigreflex-amarelo.jpg'),
  ('004944', 'Tigre', '/produtos/tigre/eletroduto-corrugado-tigreflex-amarelo.jpg'),
  ('004953', 'Portokoll', '/produtos/portokoll/ARGAMASSA PREMIUM PISCINAS 20KG PORTOKOLL.webp'),
  ('004959', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('004993', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-27-36-tigre.jpg'),
  ('004997', 'Tigre', '/produtos/tigre/duto-tigreflex-azul.jpg'),
  ('005065', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL AZUL COBALTO BD 1KG PORTOKOLL.png'),
  ('005066', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI PISCINA AZUL PISC 1KG PORTOKOLL.webp'),
  ('005078', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005080', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005082', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('005086', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-normal-tigre.jpg'),
  ('005087', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL PRETO INTE 1KG PORTOKOLL.webp'),
  ('005089', 'Tigre', '/produtos/tigre/te-soldavel-tigre.jpg'),
  ('005090', 'Tigre', '/produtos/tigre/te-reducao-soldavel-tigre.jpg'),
  ('005091', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('005094', 'Tigre', '/produtos/tigre/joelho-90-transicao-aquatherm-tigre.jpg'),
  ('005095', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('005109', 'Tigre', '/produtos/tigre/curva-transposicao-aquatherm-tigre.jpg'),
  ('005110', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('005115', 'Tigre', '/produtos/tigre/joelho-90-aquatherm-tigre.jpg'),
  ('005117', 'Tigre', '/produtos/tigre/te-misturador-transicao-aquatherm-tigre.jpg'),
  ('005118', 'Tigre', '/produtos/tigre/te-90-aquatherm-tigre.jpg'),
  ('005142', 'Tigre', '/produtos/tigre/joelho-45-soldavel-tigre.jpg'),
  ('005143', 'Tigre', '/produtos/tigre/joelho-90-soldavel-tigre.jpg'),
  ('005149', 'Tigre', '/produtos/tigre/joelho-45-esgoto-serie-normal-tigre.jpg'),
  ('005150', 'Tigre', '/produtos/tigre/curva-90-curta-esgoto-serie-normal-tigre.jpg'),
  ('005151', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005154', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('005159', 'Tigre', '/produtos/tigre/joelho-90-esgoto-serie-normal-tigre.jpg'),
  ('005164', 'Tigre', '/produtos/tigre/adaptador-soldavel-anel-caixa-dagua-tigre.jpg'),
  ('005165', 'Tigre', '/produtos/tigre/adaptador-soldavel-anel-caixa-dagua-tigre.jpg'),
  ('005166', 'Tigre', '/produtos/tigre/adaptador-soldavel-anel-caixa-dagua-tigre.jpg'),
  ('005167', 'Tigre', '/produtos/tigre/joelho-90-soldavel-rosca-tigre.jpg'),
  ('005169', 'Tigre', '/produtos/tigre/tubo-soldavel-6m-tigre.jpg'),
  ('005170', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-r-6m-tigre.jpg'),
  ('005172', 'Tigre', '/produtos/tigre/tubo-esgoto-serie-normal-6m-tigre.jpg'),
  ('005175', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('005182', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-12-16-tigre.jpg'),
  ('005183', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('005193', 'Tigre', '/produtos/tigre/curva-90-soldavel-tigre.jpg'),
  ('005196', 'Krona', '/produtos/krona/tubo-esgoto-serie-reforcada-6m-krona.png'),
  ('005201', 'Tigre', '/produtos/tigre/curva-90-soldavel-tigre.jpg'),
  ('005202', 'Tigre', '/produtos/tigre/curva-90-curta-esgoto-serie-normal-dn40-tigre.jpg'),
  ('005207', 'Tigre', '/produtos/tigre/curva-90-curta-esgoto-serie-normal-tigre.jpg'),
  ('005213', 'Tigre', '/produtos/tigre/duto-tigreflex-azul.jpg'),
  ('005222', 'Tigre', '/produtos/tigre/curva-90-aquatherm-tigre.jpg'),
  ('005236', 'Krona', '/produtos/krona/caixa-gordura-dn300-krona.png'),
  ('005242', 'Ceramfix', '/produtos/ceramfix/primer-nivela-facil-5l-ceramfix.jpg'),
  ('005258', 'Tigre', '/produtos/tigre/te-90-aquatherm-tigre.jpg'),
  ('005259', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('005260', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('005261', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('005262', 'Tigre', '/produtos/tigre/te-reducao-aquatherm-tigre.jpg'),
  ('005272', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005277', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-r-tigre.jpg'),
  ('005279', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-r-tigre.jpg'),
  ('005300', 'Tigre', '/produtos/tigre/juncao-dupla-esgoto-serie-normal-100-tigre.jpg'),
  ('005316', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('005332', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('005365', 'Tigre', '/produtos/tigre/te-reducao-aquatherm-tigre.jpg'),
  ('005366', 'Tigre', '/produtos/tigre/te-reducao-aquatherm-tigre.jpg'),
  ('005367', 'Tigre', '/produtos/tigre/te-misturador-aquatherm-tigre.jpg'),
  ('005368', 'Tigre', '/produtos/tigre/tubo-coletor-esgoto-6m-jei-tigre.jpg'),
  ('005369', 'Tigre', '/produtos/tigre/tubo-coletor-esgoto-6m-jei-tigre.jpg'),
  ('005370', 'Tigre', '/produtos/tigre/tubo-coletor-esgoto-6m-jei-tigre.jpg'),
  ('005386', 'Tigre', '/produtos/tigre/tubo-ppr-pn12-tigre.jpg'),
  ('005387', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-marrom-corfio.png'),
  ('005393', 'Tigre', '/produtos/tigre/joelho-90-soldavel-bucha-latao-tigre.jpg'),
  ('005394', 'Tigre', '/produtos/tigre/joelho-90-ppr-tigre.jpg'),
  ('005395', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005396', 'Tigre', '/produtos/tigre/juncao-simples-esgoto-serie-normal-tigre.jpg'),
  ('005401', 'Tigre', '/produtos/tigre/joelho-90-aquatherm-tigre.jpg'),
  ('005402', 'Tigre', '/produtos/tigre/te-90-aquatherm-tigre.jpg'),
  ('005403', 'Tigre', '/produtos/tigre/conector-aquatherm-tigre.jpg'),
  ('005404', 'Tigre', '/produtos/tigre/conector-aquatherm-tigre.jpg'),
  ('005407', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('005410', 'Tigre', '/produtos/tigre/joelho-90-aquatherm-tigre.jpg'),
  ('005412', 'Tigre', '/produtos/tigre/conector-aquatherm-tigre.jpg'),
  ('005414', 'Tigre', '/produtos/tigre/joelho-90-transicao-aquatherm-tigre.jpg'),
  ('005415', 'Tigre', '/produtos/tigre/conector-aquatherm-tigre.jpg'),
  ('005417', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI CINZA PLATINA 1KG PORTOKOLL.webp'),
  ('005418', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI BRANCO 1KG PORTOKOLL.webp'),
  ('005419', 'Tigre', '/produtos/tigre/ralo-saida-articulada-100x40-tigre.jpg'),
  ('005437', 'Tigre', '/produtos/tigre/curva-45-soldavel-tigre.jpg'),
  ('005438', 'Tigre', '/produtos/tigre/curva-45-soldavel-tigre.jpg'),
  ('005462', 'Docol', '/produtos/docol/valvula-retencao-vertical-1-1-2.jpg'),
  ('005514', 'Tigre', '/produtos/tigre/juncao-dupla-esgoto-serie-normal-75-tigre.jpg'),
  ('005522', 'Docol', '/produtos/docol/valvula-retencao-vertical-1.jpg'),
  ('005591', 'Tigre', '/produtos/tigre/te-reducao-aquatherm-tigre.jpg'),
  ('005645', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO AROEIRA 1KG PORTOKOLL.webp'),
  ('005649', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('005657', 'Docol', '/produtos/docol/acabamento-valvula-descarga-especial-gelo-polar.jpg'),
  ('005664', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('005667', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI PISCINA AZUL CELESTE 1KG PORTOKOLL.webp'),
  ('005668', 'Portokoll', '/produtos/portokoll/rejunte-acrilico-ligamax-gold-cinza-1kg.png'),
  ('005674', 'Docol', '/produtos/docol/valvula-saida-agua-universal-tampa-metal-cromada-docol.jpg'),
  ('005676', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005707', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005716', 'Fortlev', '/produtos/fortlev/tubo-soldavel-6m-fortlev.jpg'),
  ('005752', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('005783', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005796', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO CAMURCA 1KG PORTOKOLL.webp'),
  ('005804', 'Inkor', '/produtos/inkor/argamassa-refrataria-refrakor-5-kg-inkor.png'),
  ('005806', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005839', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('005884', 'Tigre', '/produtos/tigre/tubo-aquatherm-cpvc-tigre.jpg'),
  ('005886', 'Tigre', '/produtos/tigre/joelho-45-aquatherm-tigre.jpg'),
  ('005910', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005925', 'Krona', '/produtos/krona/tubo-cpvc-ultraterm-3m-krona.png'),
  ('005926', 'Krona', '/produtos/krona/tubo-cpvc-ultraterm-3m-krona.png'),
  ('005941', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('005947', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('005951', 'Weg', '/produtos/weg/modulo-tomada-2pt-10a-compose-weg.jpg'),
  ('005968', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('005969', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-laranja-corfio.png'),
  ('005978', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('006025', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-amarelo-corfio.png'),
  ('006045', 'Krona', '/produtos/krona/joelho-90-ultraterm-krona.png'),
  ('006058', 'Tigre', '/produtos/tigre/adaptador-soldavel-curto-bolsa-rosca-tigre.jpg'),
  ('006071', 'Eternit', '/produtos/eternit/telha-canalete-90-eternit.jpg'),
  ('006080', 'Krona', '/produtos/krona/joelho-45-ultraterm-krona.png'),
  ('006100', 'Portokoll', '/produtos/portokoll/REJUNTE AQUA FLEX PISCINA GRAFITE 4KG PORTOKOLL.webp'),
  ('006151', 'Portokoll', '/produtos/portokoll/REJUNTE ACRL CZ SIDERAL BD 1KG PORTOKOLL.webp'),
  ('006166', 'Vedacit', '/produtos/vedacit/pro-primer-mantas-18l-vedacit.png'),
  ('006186', 'Portokoll', '/produtos/portokoll/ARGAMASSA SUPERFLEX BRANCA 20KG PORTOKOLL.webp'),
  ('006188', 'Docol', '/produtos/docol/valvula-mictorio-compact-pressmatic-cromada.jpg'),
  ('006199', 'Krona', '/produtos/krona/juncao-reducao-esgoto-sn-krona.png'),
  ('006241', 'Krona', '/produtos/krona/tubo-pvc-serie-leve-6m-krona.png'),
  ('006251', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('006252', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('006253', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006254', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('006255', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('006269', 'Krona', '/produtos/krona/eletroduto-corrugado-flexivel-amarelo-krona.png'),
  ('006284', 'Krona', '/produtos/krona/registro-esfera-soldavel-compacto-krona.png'),
  ('006286', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006288', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('006290', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006291', 'Krona', '/produtos/krona/registro-esfera-soldavel-compacto-krona.png'),
  ('006292', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006294', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('006301', 'Krona', '/produtos/krona/joelho-90-transicao-rf-ultraterm-krona.png'),
  ('006302', 'Krona', '/produtos/krona/registro-esfera-soldavel-compacto-krona.png'),
  ('006304', 'Portokoll', '/produtos/portokoll/ARGAMASSA PASTILHAS E MOSAICOS 20 KG PORTOKOLL.webp'),
  ('006314', 'Krona', '/produtos/krona/te-misturador-rf-ultraterm-krona.png'),
  ('006318', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('006321', 'Eternit', '/produtos/eternit/telha-vogatex-4mm-eternit.webp'),
  ('006322', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp'),
  ('006323', 'Eternit', '/produtos/eternit/cumeeira-articulada-superior-vogatex-eternit.jpg'),
  ('006324', 'Eternit', '/produtos/eternit/cumeeira-articulada-inferior-vogatex-eternit.jpg'),
  ('006334', 'Krona', '/produtos/krona/eletroduto-corrugado-flexivel-amarelo-krona.png'),
  ('006360', 'Eternit', '/produtos/eternit/telha-canalete-49-eternit.jpg'),
  ('006370', 'Krona', '/produtos/krona/joelho-45-ultraterm-krona.png'),
  ('006386', 'Inkor', '/produtos/inkor/argamassa-ac1-20kg-inkor.png'),
  ('006392', 'Krona', '/produtos/krona/registro-esfera-soldavel-compacto-krona.png'),
  ('006435', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006436', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('006437', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('006438', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('006439', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('006487', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006488', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006489', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('006490', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006491', 'Krona', '/produtos/krona/curva-90-curta-esgoto-sn-krona.png'),
  ('006496', 'Ceramfix', '/produtos/ceramfix/rejunte-ceramica-branco-1kg-ceramfix.png'),
  ('006497', 'Ceramfix', '/produtos/ceramfix/rejunte-ceramica-cinza-1kg-ceramfix.png'),
  ('006498', 'Ceramfix', '/produtos/ceramfix/rejunte-ceramica-cinza-claro-1kg-ceramfix.png'),
  ('006499', 'Ceramfix', '/produtos/ceramfix/rejunte-epoxi-branco-500g-ceramfix.png'),
  ('006500', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006505', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006531', 'Inkor', '/produtos/inkor/primer-selador-autonivelante-18l-inkor.png'),
  ('006539', 'Portokoll', '/produtos/portokoll/REJUNTE EXT FINO AMENDOLA 1KG PORTOKOLL - Copia.webp'),
  ('006541', 'Krona', '/produtos/krona/joelho-90-roscavel-krona.png'),
  ('006549', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('006550', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('006551', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006552', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-azul-corfio.webp'),
  ('006553', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-branco-corfio.png'),
  ('006554', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-preto-corfio.png'),
  ('006555', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006556', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-vermelho-corfio.png'),
  ('006565', 'Eternit', '/produtos/eternit/telha-canalete-90-eternit.jpg'),
  ('006572', 'Docol', '/produtos/docol/cuba-invicta-37x34x18-inox-304-docol.jpg'),
  ('006588', 'Krona', '/produtos/krona/joelho-90-roscavel-krona.png'),
  ('006677', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('006684', 'Portokoll', '/produtos/portokoll/REJUNTE EPOXI CINZA BASALTO 1KG LIGAMAX SIKA.webp'),
  ('006686', 'Inkor', '/produtos/inkor/argamassa-koll-mais-ac3-20-kg-inkor.png'),
  ('006688', 'Tigre', '/produtos/tigre/quadro-distribuicao-embutir-18-24-tigre.jpg'),
  ('006696', 'Vedacit', '/produtos/vedacit/vedatop-rodape-12kg-vedacit.webp'),
  ('006706', 'Docol', '/produtos/docol/ducha-higienica-nova-pertutti-cromada-docol.jpg'),
  ('006745', 'Corfio', '/produtos/corfio/cabo-pp-500v-4x4mm-preto-corfio.jpg'),
  ('006746', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('006755', 'Krona', '/produtos/krona/eletroduto-corrugado-reforcado-laranja-krona.png'),
  ('006756', 'Krona', '/produtos/krona/torneira-boia-caixa-dagua-krona.png'),
  ('006760', 'Krona', '/produtos/krona/adaptador-caixa-dagua-soldavel-krona.png'),
  ('006761', 'Krona', '/produtos/krona/adaptador-caixa-dagua-soldavel-krona.png'),
  ('006762', 'Krona', '/produtos/krona/adaptador-caixa-dagua-soldavel-krona.png'),
  ('006763', 'Krona', '/produtos/krona/adaptador-caixa-dagua-soldavel-krona.png'),
  ('006764', 'Krona', '/produtos/krona/adaptador-caixa-dagua-soldavel-krona.png'),
  ('006765', 'Krona', '/produtos/krona/adaptador-curto-soldavel-krona.png'),
  ('006766', 'Krona', '/produtos/krona/adaptador-curto-soldavel-krona.png'),
  ('006767', 'Krona', '/produtos/krona/adaptador-curto-soldavel-krona.png'),
  ('006768', 'Krona', '/produtos/krona/adaptador-curto-soldavel-krona.png'),
  ('006811', 'Krona', '/produtos/krona/curva-90-soldavel-krona.png'),
  ('006812', 'Krona', '/produtos/krona/curva-90-curta-esgoto-sn-krona.png'),
  ('006813', 'Krona', '/produtos/krona/curva-90-curta-esgoto-sn-krona.png'),
  ('006814', 'Krona', '/produtos/krona/curva-90-soldavel-krona.png'),
  ('006815', 'Krona', '/produtos/krona/curva-90-soldavel-krona.png'),
  ('006816', 'Krona', '/produtos/krona/curva-90-soldavel-krona.png'),
  ('006817', 'Krona', '/produtos/krona/curva-90-soldavel-krona.png'),
  ('006818', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('006819', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('006820', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('006821', 'Krona', '/produtos/krona/joelho-45-soldavel-krona.png'),
  ('006822', 'Krona', '/produtos/krona/joelho-45-soldavel-krona.png'),
  ('006823', 'Krona', '/produtos/krona/joelho-45-soldavel-krona.png'),
  ('006824', 'Krona', '/produtos/krona/joelho-45-soldavel-krona.png'),
  ('006836', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('006837', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('006838', 'Krona', '/produtos/krona/joelho-90-anel-esgoto-sn-krona.png'),
  ('006839', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('006840', 'Krona', '/produtos/krona/joelho-90-esgoto-sn-krona.png'),
  ('006841', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('006842', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('006843', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('006844', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('006845', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('006846', 'Krona', '/produtos/krona/joelho-90-soldavel-bucha-latao-krona.png'),
  ('006847', 'Krona', '/produtos/krona/joelho-90-soldavel-bucha-latao-krona.png'),
  ('006848', 'Krona', '/produtos/krona/juncao-esgoto-sn-krona.png'),
  ('006849', 'Krona', '/produtos/krona/juncao-esgoto-sn-krona.png'),
  ('006850', 'Krona', '/produtos/krona/juncao-esgoto-sn-krona.png'),
  ('006851', 'Krona', '/produtos/krona/juncao-esgoto-sn-krona.png'),
  ('006852', 'Krona', '/produtos/krona/juncao-reducao-esgoto-sn-krona.png'),
  ('006853', 'Krona', '/produtos/krona/juncao-reducao-esgoto-sn-krona.png'),
  ('006854', 'Krona', '/produtos/krona/juncao-reducao-esgoto-sn-krona.png'),
  ('006874', 'Krona', '/produtos/krona/te-reducao-esgoto-sn-krona.png'),
  ('006878', 'Krona', '/produtos/krona/te-reducao-soldavel-krona.png'),
  ('006879', 'Krona', '/produtos/krona/te-reducao-soldavel-krona.png'),
  ('006880', 'Krona', '/produtos/krona/te-reducao-soldavel-krona.png'),
  ('006881', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('006882', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('006883', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('006884', 'Krona', '/produtos/krona/te-soldavel-krona.png'),
  ('006885', 'Krona', '/produtos/krona/te-soldavel-bucha-latao-krona.png'),
  ('006886', 'Krona', '/produtos/krona/te-soldavel-bucha-latao-krona.png'),
  ('006887', 'Krona', '/produtos/krona/tubo-esgoto-serie-normal-6m-krona.png'),
  ('006888', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006889', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006890', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006891', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006892', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006893', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('006909', 'Krona', '/produtos/krona/tubo-ppr-pn20-3m-krona.png'),
  ('006911', 'Krona', '/produtos/krona/joelho-90-ff-ppr-krona.png'),
  ('006912', 'Krona', '/produtos/krona/joelho-45-ff-ppr-krona.png'),
  ('006913', 'Krona', '/produtos/krona/adaptador-transicao-ff-inserto-ppr-krona.png'),
  ('006914', 'Krona', '/produtos/krona/adaptador-transicao-fm-inserto-ppr-krona.png'),
  ('006920', 'Docol', '/produtos/docol/registro-gaveta-abnt-2.jpg'),
  ('006924', 'Krona', '/produtos/krona/quadro-distribuicao-embutir-sem-barramento-krona.png'),
  ('006928', 'Krona', '/produtos/krona/curva-transposicao-soldavel-krona.png'),
  ('006929', 'Krona', '/produtos/krona/ralo-quadrado-oculto-10x10-krona.png'),
  ('006930', 'Krona', '/produtos/krona/valvula-retencao-esgoto-sn-krona.png'),
  ('006944', 'Docol', '/produtos/docol/registro-gaveta-industrial-3.jpg'),
  ('006948', 'Krona', '/produtos/krona/tubo-ppr-pn20-3m-krona.png'),
  ('006949', 'Krona', '/produtos/krona/joelho-90-ff-ppr-krona.png'),
  ('006950', 'Krona', '/produtos/krona/joelho-45-ff-ppr-krona.png'),
  ('006965', 'Krona', '/produtos/krona/curva-90-esgoto-sr-krona.png'),
  ('006966', 'Krona', '/produtos/krona/curva-90-esgoto-sr-krona.png'),
  ('006968', 'Krona', '/produtos/krona/joelho-90-ff-ppr-krona.png'),
  ('006969', 'Krona', '/produtos/krona/joelho-90-ff-ppr-krona.png'),
  ('006970', 'Krona', '/produtos/krona/joelho-45-ff-ppr-krona.png'),
  ('007025', 'Corfio', '/produtos/corfio/cabo-cobre-nu-mole-corfio.png'),
  ('007043', 'Krona', '/produtos/krona/joelho-45-esgoto-sn-krona.png'),
  ('007070', 'Portokoll', '/produtos/portokoll/ARGAMASSA MULTIUSO 12X1 AC3 20KG PORTOKOLL.webp'),
  ('007071', 'Krona', '/produtos/krona/tubo-pvc-soldavel-6m-krona.png'),
  ('007073', 'Krona', '/produtos/krona/joelho-90-soldavel-krona.png'),
  ('007074', 'Krona', '/produtos/krona/joelho-45-soldavel-krona.png'),
  ('007085', 'Corfio', '/produtos/corfio/cabo-flexivel-1-5mm-verde-corfio.png'),
  ('007101', 'Krona', '/produtos/krona/joelho-90-mf-inserto-ppr-krona.png'),
  ('007102', 'Krona', '/produtos/krona/joelho-90-ff-ppr-krona.png'),
  ('007103', 'Krona', '/produtos/krona/te-reducao-central-fff-ppr-krona.png'),
  ('007104', 'Krona', '/produtos/krona/tubo-ppr-pn20-3m-krona.png'),
  ('007105', 'Krona', '/produtos/krona/tubo-ppr-pn20-3m-krona.png'),
  ('007108', 'Krona', '/produtos/krona/tubo-ppr-pn20-3m-krona.png'),
  ('007109', 'Eternit', '/produtos/eternit/telha-ondulada-eternit.webp')
)
update public.products as product
set foto_url = imported.foto_url,
    manufacturer_id = manufacturer.id
from imported
join public.manufacturers as manufacturer
  on lower(manufacturer.nome) = lower(imported.manufacturer_name)
where product.sku = imported.sku
  and product.foto_url is null;
